### ISSUE TITLE
[RAHI] UAT Feedback

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/RAHI#11]
- [x] Remove Age of mother field from Registration.
- [x] In Livelihood encounter, for question "What productive assets does the household own?" when answer is Others, give option to specify Others.
- [x] Same as above for question "Crops produced by Household" in Livelihood encounter.
- [x] In encounter collecting water details, for question "What sources of water do you use for washing" should give option to specify others when Others is selected.
- [x] If answer to "Do you treat water before drinking?" is No, then other questions in the page should not be displayed.
- [x] Add encounter eligibility check for all the encounters to be only filled once. Once filled, they should not show in new forms. 
- [x] For "What is the primary and secondary source of drinking water" question, mark all the water sources as non-mandatory items.

**Comment by utkarshavni** [comment]
Added one item.

**Comment by AchalaBelokar** [comment]
Blocked because of this   https://app.zenhub.com/workspaces/product-635b73bded85e50018871ae6/issues/avniproject/avni-client/749
