### ISSUE TITLE
[RAHI] Shift Individual encounters to Household encoutners

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/RAHI#13]
- [x] Encounters/Forms mentioned below are against Individual, remove them from there and map them to Household subject. 
- Pregnant Woman
- Nutrition - Infant feeding
- [x] Allow form to be filled once only.

**Comment by AchalaBelokar** [comment]
- [ ] Currently  it is showing in individual which is not registered in household

**Comment by AchalaBelokar** [comment]
- [x] Nutrition - Infant feeding is not appearing .
