### ISSUE TITLE
[RAHI Support] Setup longitudinal export for the Household registration form 

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/RAHI#17]
Product card for reference - https://github.com/avniproject/avni-server/issues/547

- [x] Setup longitudinal export for the Household registration form, since it has repeatable QG form element in it.

**Comment by BEULAHEVANJALIN** [comment]
Need to pair with someone to understand longitudinal export

**Comment by nupoorkhandelwal** [comment]
It has a product bug -{
  "individual": {
    "uuid": "82e97745-a0cb-4af0-be75-e980d065c7ce",
    "fields": [
      "id",
      "uuid",
      "firstName",
      "registrationDate"
    ],
    "filters": {
      "addressLevelIds": [],
      "date": {
        "from": "2020-01-12",
        "to": "2022-05-04"
      }
    }
  },
  "timezone": "Asia/Calcutta"
}


https://github.com/avniproject/avni-webapp/issues/1051

**Comment by Gojo-Taqi** [comment]
@Dinesh2019 you can use the following to verify changes
```
{
"individual": {
"uuid": "82e97745-a0cb-4af0-be75-e980d065c7ce",
"fields": [
"id",
"uuid",
"firstName",
"registrationDate"
],
"filters": {
"addressLevelIds": [],
"date": {
"from": "2023-01-01",
"to": "2023-05-28"
}
}
},
"timezone": "Asia/Calcutta"
}
```
