### ISSUE TITLE
[RAHI] Household  Mortality and Morbidity data

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/RAHI#4]
Create an encounter called Mortality and Morbidity data against Household subject.

Form name - Mortality and Morbidity data
https://drive.google.com/drive/u/1/folders/1iSgfsg3-VvAIfUVG3EkWKpapHcYX61JJ

**Comment by Gojo-Taqi** [comment]
ETC :- 45 min
Completed in :- 33 min

**Comment by AchalaBelokar** [comment]
- [x] Has anyone in the HH, between 5-14 years of age, expired in the last 1 year? skip logic is missing that question
