### ISSUE TITLE
[RAHI] Household -  Infant feeding

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/RAHI#5]
Create an encounter called Infant feeding against the subject Individual.

Form name - Infant Feeding
https://drive.google.com/drive/u/1/folders/1iSgfsg3-VvAIfUVG3EkWKpapHcYX61JJ

**Comment by AchalaBelokar** [comment]
Unable to see this encounter

**Comment by Gojo-Taqi** [comment]
Try for an individual whose age is less than 6 years.
