### ISSUE TITLE
[RAHI] Household - Healthcare availability, affordability and accessibility

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/RAHI#6]
Create an encounter called Healthcare availability, affordability and accessibility against the subject Household.

Form name - Healthcare availability, affordability and accessibility.
https://drive.google.com/drive/u/1/folders/1iSgfsg3-VvAIfUVG3EkWKpapHcYX61JJ

**Comment by Gojo-Taqi** [comment]
ETC :- 45 min
Time taken to complete :- 1 hr 10 min

**Comment by Gojo-Taqi** [comment]
There is a small doubt in the last question of this form.
Will confirm with the BA once on this

**Comment by AchalaBelokar** [comment]
- [ ]How would you rate access to information on available healthcare services from the following sources or channels? Select only one option for each source.
The tv option is missing for this question.

- [x] In the past 12 months, how did you cover expenses for healthcare?after this question
 Regular income was enough to cover
Loan from money lender this option needed currently  it is showing another que .
