### ISSUE TITLE
[RAHI] Household - Water availability, affordability and accessibility

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/RAHI#7]
Create an encounter called Water availability, affordability and accessibility.

Form name - Water availability, affordability and accessibility.
https://drive.google.com/drive/u/1/folders/1iSgfsg3-VvAIfUVG3EkWKpapHcYX61JJ

**Comment by AchalaBelokar** [comment]
- [x] What water sources do you use for washing? Tick only one that applies should be single select.

- [ ] How is your access to water now compared to last month? Prompt for enumerator:
prompt for enumerator is missing

- [x] Do you treat water before drinking? if the answer is yes then only the question needs to show, how do you usually treat your drinking water?

**Comment by Gojo-Taqi** [comment]
For both the first and second point, I think they are fine by the way they are.
But still if they want me to change, they would include the changes in UAT feedbacks.
SO right now pushing it back to QA failed.
