### ISSUE TITLE
[RAHI] Household - Sanitaiton and Hygiene

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/RAHI#8]
Create an encounter called Sanitation and Hygiene against the subject Household.

Form name - Sanitation and Hygiene
https://drive.google.com/drive/u/1/folders/1iSgfsg3-VvAIfUVG3EkWKpapHcYX61JJ

**Comment by Gojo-Taqi** [comment]
Estimated time of completion :- 1 hr
Time taken :- 1.5 hr
